### PR TITLE
updated the ticker showcase

### PR DESCRIPTION
**Pull request by Rahul139-stack**

### CODE REVIEW

**Comment by Harikarthyk** [comment]
Please attach the screenshot of the showcase page.

**Comment by Rahul139-stack** [comment]
> Please attach the screenshot of the showcase page.

image

**Comment by Harikarthyk** [comment]
Where is the showcase for the 3x3 ticker?

and in the above screenshot, I can see that the icon for the primary ticker is not coming. Can you please check that?

**Comment by Rahul139-stack** [comment]
> Where is the showcase for the 3x3 ticker?
> 
> and in the above screenshot, I can see that the icon for the primary ticker is not coming. Can you please check that?

For 3*3 ticker showcase, we need container to implement, code need to merge from @Harikarthyk side.Once it get merged ,then I will implement that.

**Comment by Harikarthyk** [comment]
Ok, what about Icons?

**Comment by wildone** [comment]
what about tests?

**Pull request merged**
