### PR TITLE
Feature/add readme for components

### PR DESCRIPTION
**Pull request by Shivam-apna**
added README for widgets components.

- [Chart README.md](https://github.com/typerefinery-ai/typerefinery-websight/blob/25a177ba067fde1f728700ef46cb5d4b92e06b90/application/backend/src/main/resources/apps/typerefinery/components/widgets/chart/README.md
)
- [Ticker README.md](https://github.com/typerefinery-ai/typerefinery-websight/blob/25a177ba067fde1f728700ef46cb5d4b92e06b90/application/backend/src/main/resources/apps/typerefinery/components/widgets/ticker/README.md)
- [Editor README.md](https://github.com/typerefinery-ai/typerefinery-websight/blob/25a177ba067fde1f728700ef46cb5d4b92e06b90/application/backend/src/main/resources/apps/typerefinery/components/widgets/editor/README.md)
- [Search README.md](https://github.com/typerefinery-ai/typerefinery-websight/blob/25a177ba067fde1f728700ef46cb5d4b92e06b90/application/backend/src/main/resources/apps/typerefinery/components/widgets/search/README.md)

### CODE REVIEW

**Review by Harikarthyk — CHANGES_REQUESTED** [review]
In ticker why there is no any title for the 4th column
image

And Please add the sample Image for the variants, for eg refer map readme.

**Review by Harikarthyk — CHANGES_REQUESTED** [review]
image

I could not see the variants screenshots, you can take look at map readme,

For default value use enabled and disabled, follow same conventions for all.

**Comment by wildone** [comment]
@Shivam-apna is this done?

**Comment by Shivam-apna** [comment]
> @Shivam-apna is this done?

yes

**Pull request merged**
